const languageIconsImage = {
  plaintext: "/icons/txt.svg",
  javascript: "/icons/js.svg",
  javascriptreact: "/icons/jsx.svg",
  typescript: "/icons/ts.svg",
  typescriptreact: "/icons/tsx.svg",
  html: "/icons/html.svg",
  css: "/icons/css.svg",
  scss: "/icons/scss.svg",
  shell: "/icons/shell.svg",
  json: "/icons/json.svg",
  markdown: "/icons/md.svg",
  python: "/icons/python.svg",
  java: "/icons/java.svg",
  ruby: "/icons/ruby.svg",
  go: "/icons/go.svg",
  c: "/icons/c.svg",
  cpp: "/icons/cpp.svg",
  csharp: "/icons/csharp.svg",
  php: "/icons/php.svg",
  swift: "/icons/swift.svg",
  kotlin: "/icons/kotlin.svg",
  rust: "/icons/rust.svg",
  dart: "/icons/dart.svg",
  r: "/icons/r.svg",
  scala: "/icons/scala.svg",
  perl: "/icons/perl.svg",
  lua: "/icons/lua.svg",
  groovy: "/icons/groovy.svg",
  powershell: "/icons/powershell.svg",
  sql: "/icons/mysql.svg",
  prisma: "/icons/prisma.svg",
};

export { languageIconsImage };
