const languageShortNames = {
	plaintext: "TXT",
	javascript: "JS",
	javascriptreact: "JSX",
	typescript: "TS",
	typescriptreact: "TSX",
	html: "HTML",
	css: "CSS",
	scss: "SCSS",
	shell: "SHELL",
	json: "JSON",
	markdown: "MD",
	python: "PYTHON",
	java: "JAVA",
	ruby: "RB",
	go: "GO",
	c: "C",
	cpp: "C++",
	csharp: "C#",
	php: "PHP",
	swift: "SWIFT",
	kotlin: "KT",
	rust: "RUST",
	dart: "DART",
	r: "R",
	scala: "SCALA",
	perl: "PL",
	lua: "LUA",
	groovy: "GRV",
	powershell: "PS",
	sql: "SQL",
	bash: "BASH",
	yaml: "YAML",
	haskell: "HS",
	dockerfile: "DOCKERFILE",
	assemblyscript: "ASM",
	ejs: "EJS",
	prisma: "PRISMA",
	zig: "ZIG",
};

export default languageShortNames;
